config/routes.rb
Rails.application.routes.draw do

  
  namespace 'api' do
    namespace 'v1' do
  
      resources :personas
      resources :usuarios
  
    end
  end  
    
  #CRONTAB
  get "crontab_ultron/index"

  #JURISDICCIONES
  get "jurisdicciones/index"
  get "jurisdicciones/buscar_juridisccion_oferta" 

  #JURISDICCIONES
  get "informes/index"
  get "informes/indexa"
  get "informes/generar_pdf"

  #DETALLES DEBITOS
  post "detalles_debitos/lista"
  get "detalles_debitos/lista"
  get "detalles_debitos/agregar"
  post "detalles_debitos/guardar"
  get "detalles_debitos/eliminar"
  get "detalles_debitos/editar"
  post "detalles_debitos/actualizar"
  get "detalles_debitos/index"
 
  #DETALLES CREDITOS
  post "detalles_creditos/lista"
  get "detalles_creditos/lista"
  get "detalles_creditos/agregar"
  post "detalles_creditos/guardar"
  get "detalles_creditos/eliminar"
  get "detalles_creditos/editar"
  post "detalles_creditos/actualizar"
  get "detalles_creditos/index"

  #PRODUCCION
  get "produccion/index"
  get "produccion/lista"
  post "produccion/lista"
  get "produccion/agregar"
  post "produccion/guardar"
  get "produccion/eliminar"
  get "produccion/editar"
  post "produccion/actualizar"
  get "produccion/produccion_detalle_credito"
  get "produccion/produccion_detalle_debito"
  get "produccion/agregar_detalle_credito"
  get "produccion/agregar_detalle_debito"
  post "produccion/guardar_detalle_credito"
  post "produccion/guardar_detalle_debito"
  get "produccion/eliminar_produccion_detalle_credito"
  get "produccion/eliminar_produccion_detalle_debito"
  get "produccion/cambiar_estado_solicitado_a_en_progreso"
  get "produccion/cambiar_estado_en_progreso_a_finalizado"
  get "produccion/cambiar_estado_cobro"
  get "produccion/cambiar_estado_cobro_desconfirmar"
  get "produccion/planilla_resumen_produccion"
  get "produccion/planilla_resumen_produccion_pdf"
  get "produccion/planilla_resumen_produccion_cliente"
  get "produccion/planilla_resumen_produccion_cliente_pdf"
  
  #PACIENTES
  post "pacientes/lista"
  get "pacientes/lista"
  get "pacientes/agregar"
  post "pacientes/guardar"
  get "pacientes/eliminar"
  get "pacientes/editar"
  post "pacientes/actualizar"
  get "pacientes/index"
  get "pacientes/buscar_paciente"
  get "pacientes/buscar_persona"
  get "pacientes/buscar_paciente_cita"

  #PACIENTES DETALLES FONO
  get "pacientes_detalles_fono/paciente_detalle_fono"
  post "pacientes_detalles_fono/guardar_detalle_fono"

  #HISTORIALES PACIENTES
  post "historiales_pacientes/lista_pacientes"
  get "historiales_pacientes/lista_pacientes"
  get "historiales_pacientes/index"
  get "historiales_pacientes/historial_paciente_detalle_fono"
  get "historiales_pacientes/lista_citas"
  post "historiales_pacientes/lista_citas"
  get "historiales_pacientes/historial_cita_detalle_fono_terminado"
  


  #PROFESIONALES
  post "profesionales/lista"
  get "profesionales/lista"
  get "profesionales/agregar"
  post "profesionales/guardar"
  get "profesionales/eliminar"
  get "profesionales/editar"
  post "profesionales/actualizar"
  get "profesionales/index"
  get "profesionales/buscar_profesional"
  get "profesionales/buscar_persona"
  
  #TUTORES
  post "tutores/lista"
  get "tutores/lista"
  get "tutores/agregar"
  post "tutores/guardar"
  get "tutores/eliminar"
  get "tutores/editar"
  post "tutores/actualizar"
  get "tutores/index"
  get "tutores/buscar_tutor"
  get "tutores/buscar_persona"
  get "tutores/tutor_detalle"
  get "tutores/agregar_tutor_detalle"
  post "tutores/guardar_tutor_detalle"
  get "tutores/eliminar_tutor_detalle"

  #PRECIOS
  post "precios/lista"
  get "precios/lista"
  get "precios/agregar"
  post "precios/guardar"
  get "precios/eliminar"
  get "precios/editar"
  post "precios/actualizar"
  get "precios/index"
  get "precios/obtener_datos"
  get "precios/buscar_precio"
  get "precios/marcar_predeterminado"

  #CITAS
  get "citas/index"
  post "citas/lista"
  get "citas/lista"
  get "citas/agregar"
  post "citas/guardar"
  get "citas/editar"
  post "citas/actualizar"
  get "citas/eliminar"
  get "citas/cambiar_estado_cita_en_espera_a_en_consultorio"
  get "citas/cambiar_estado_cita_en_consultorio_a_terminado"
  get "citas/cambiar_estado_cobro_a_cobrado"
  get "citas/cambiar_estado_cobro_a_no_cobrado"
  get "citas/cambiar_estado_cita_terminado_a_en_consultorio"
  get "citas/postergar_cita"
  post "citas/guardar_postergar_cita"
  get "citas/imprimir_informe"
  get "citas/generar_informe_pdf"
  get "citas/cambiar_estado_cita_en_consultorio_a_en_espera"
  

  #CITAS DETALLES FONO
  get "citas_detalles_fono/cita_detalle_fono"
  post "citas_detalles_fono/guardar_cita_detalle_fono"
  get "citas_detalles_fono/emitir_resolucion"
  post "citas_detalles_fono/guardar_resolucion"
  get "citas_detalles_fono/adjuntar_resolucion"
  post "citas_detalles_fono/guardar_resolucion_adjunta"
  get "citas_detalles_fono/habilitar_descarga_archivo"
  get "citas_detalles_fono/deshabilitar_descarga_archivo"
  get "citas_detalles_fono/cita_detalle_fono_terminado"
  
  #PERSONAS
  post "personas/lista"
  get "personas/lista"
  get "personas/agregar"
  get "personas/agregar_persona_senatics"
  post "personas/guardar"
  post "personas/guardar_persona_senatics"
  get "personas/eliminar"
  get "personas/editar"
  post "personas/actualizar"
  get "personas/index"
  get "personas/mostrar_formulario"
  post "personas/unificar_persona"
  get "personas/obtener_datos"
  get "personas/buscar_persona_senatics"
  get "personas/buscar_chofer"
  

  #ROLES
  post "roles/lista"
  get "roles/lista"
  get "roles/agregar"
  post "roles/guardar"
  get "roles/eliminar"
  get "roles/editar"
  post "roles/actualizar"
  get "roles/accesos"
  get "roles/agregar_acceso"
  get "roles/guardar_acceso"
  get "roles/eliminar_acceso"
  get "roles/index"

  
  #CONTROLADORES
  post "controladores/lista"
  get "controladores/lista"
  get "controladores/agregar"
  post "controladores/guardar"
  get "controladores/eliminar"
  get "controladores/editar"
  post "controladores/actualizar"
  get "controladores/acciones"
  get "controladores/agregar_accion"
  post "controladores/guardar_accion"
  get "controladores/eliminar_accion"
  get "controladores/index"

  
  #USUARIOS
  get "usuarios/cambiar_perfil_actual"
  get "usuarios/mi_cuenta"
  post "usuarios/actualizar_mi_cuenta"
  post "usuarios/actualizar_mi_password"
  get "usuarios/perfiles"
  get "usuarios/agregar_perfil"
  get "usuarios/guardar_perfil"
  get "usuarios/eliminar_perfil"
  post "usuarios/actualizar_password"
  get "usuarios/reset_password"
  get "usuarios/perfiles"
  get 'usuarios/index'
  get 'usuarios/lista'
  post 'usuarios/lista'
  get "usuarios/agregar"
  post "usuarios/guardar"
  get "usuarios/eliminar"
  get "usuarios/editar"
  post "usuarios/actualizar"
  get 'usuarios/buscar_persona'
  post 'usuarios/cambiar_estado_usuario'

  #LOGIN
  get 'login' => "usuarios_sessions#new",      :as => :login
  get 'logout' => "usuarios_sessions#destroy", :as => :logout
  post "usuarios_sessions/create"
  get "usuarios_sessions/acceso_denegado"
  get "usuarios_sessions/new"  
  get "usuarios_sessions/mantenimiento"  

  get "principal/buscar_institucion"
  get "principal/buscar_persona"
  get "principal/buscar_usuario"
  post "principal/guardar_recuperar_password"
  get "principal/recuperar_password"
  post "principal/guardar_usuario"
  get "principal/activar_cuenta"
  get "principal/agregar_usuario"
  get "contactos" => "principal#contactos", :as => :contactos
  get "index" => "principal#index", :as => :index
  get "about" => "principal#about", :as => :about
  get "legal" => "principal#legal", :as => :legal
  get "index" => "principal#index", :as => :indexv
	
	

  root 'principal#index'
  
  get "application/autocompletar" => 'application#autocompletar', :as => :autocompletar

  #INFORMACIONES
  get "informaciones/index"
  get "informaciones/lista"
  post "informaciones/lista"
	get "informaciones/perfiles"
	get "informaciones/enlaces"
  get "informaciones/agregar"
  post "informaciones/guardar"
	get "informaciones/agregar_enlace"
	get "informaciones/guardar_enlace"
	post "informaciones/guardar_enlace"
	get "informaciones/agregar_perfil"
  get "informaciones/guardar_perfil"
  get "informaciones/eliminar"
  get "informaciones/editar"
  post "informaciones/actualizar"
	get "informaciones/editar_enlace"
	post "informaciones/actualizar_enlace"
  get "informaciones/eliminar_enlace"
  get "informaciones/eliminar_rol"

end

app/controllers/tutores_controller.rb
class TutoresController < ApplicationController

before_filter :require_usuario
skip_before_action :verify_authenticity_token

  def index
  

  end
 
  def lista

    cond = []
    args = []

    if params[:form_buscar_tutor_id].present?

      cond << "tutor_id = ?"
      args << params[:form_buscar_tutor_id]

    end

    if params[:form_buscar_tutor_documento].present?

      cond << "documento_persona = ?"
      args << params[:form_buscar_tutor_documento]

    end

    if params[:form_buscar_tutor_nombre].present?

      cond << "nombre_persona ilike ?"
      args << "%#{params[:form_buscar_tutor_nombre]}%"

    end

    if params[:form_buscar_tutor_apellido].present?

      cond << "apellido_persona ilike ?"
      args << "%#{params[:form_buscar_tutor_apellido]}%"

    end

    if params[:form_buscar_tutor_direccion].present?

      cond << "direccion ilike ?"
      args << "%#{params[:form_buscar_tutor_direccion]}%"

    end

    if params[:form_buscar_tutor_telefono].present?

      cond << "telefono ilike ?"
      args << "%#{params[:form_buscar_tutor_telefono]}%"

    end

    cond = cond.join(" and ").lines.to_a + args if cond.size > 0

    if cond.size > 0

      @tutores =  VTutor.orden_01.where(cond).paginate(per_page: 10, page: params[:page])
      @total_encontrados = VTutor.where(cond).count

    else
     
      @tutores = VTutor.orden_01.paginate(per_page: 10, page: params[:page])
      @total_encontrados = VTutor.count

    end

    @total_registros = VTutor.count

    respond_to do |f|
      
     f.js
      
    end

  end

  def agregar

    @tutor = VTutor.new

    respond_to do |f|
      
        f.js
      
    end

  end

  def guardar

    @valido = true
    @msg = ""
    @guardado_ok = false

    unless params[:persona_documento].present?

      @valido = false
      @msg += " Debe Completar el campo Documento. \n"

    end

    if @valido
      
      @tutor = Tutor.new()
      @tutor.persona_id = params[:persona_id]

        if @tutor.save

          auditoria_nueva("registrar tutor", "tutores", @tutor)
          @guardado_ok = true
         
        end 

    end
  
    rescue Exception => exc  
    # dispone el mensaje de error 
    #puts "Aqui si muestra el error ".concat(exc.message)
      if exc.present?        
        @excep = exc.message.split(':')    
        @msg = @excep[3].concat(" "+@excep[4].to_s)
      
      end                
              
    respond_to do |f|
      
        f.js
      
    end

  end

  def editar
    
    @tutor = Persona.find(params[:id])

    respond_to do |f|
      
        f.js
      
    end

  end

  def actualizar

    valido = true
    @msg = ""

    @persona = Persona.find(params[:persona][:id])
    @tutor = Tutor.where("persona_id = ?", params[:persona][:id]).first
    auditoria_id = auditoria_antes("actualizar persona", "personas", @persona)

    if valido

      @persona.update_attributes(params[:persona] )
      auditoria_despues(@persona, auditoria_id)

      if @persona.save

        @persona_ok = true

      end
    
    end
    
    rescue Exception => exc  
      # dispone el mensaje de error 
      #puts "Aqui si muestra el error ".concat(exc.message)
      if exc.present?        
        
        @excep = exc.message.split(':')    
        @msg = @excep[3].concat(" "+@excep[4])
      
      end                
        
    respond_to do |f|

      f.js

    end

  end

  def buscar_tutor
    
    @personas = VTutor.where("nombre_persona ilike ?", "%#{params[:cliente_produccion]}%")

    respond_to do |f|
      
      f.html
      f.json { render :json => @personas }
    
    end
    
  end

  def eliminar

    @valido = true
    @msg = ""

    @tutor = Tutor.find(params[:id])

    @tutor_elim = @tutor  

    if @valido

      if @tutor.destroy

        auditoria_nueva("eliminar tutor", "tutores", @tutor)

        @eliminado = true

      else

        @msg = "ERROR: No se ha podido eliminar el tutor."

      end

    end

        rescue Exception => exc  
        # dispone el mensaje de error 
        #puts "Aqui si muestra el error ".concat(exc.message)
        if exc.present?        
          
          @excep = exc.message.split(':')    
          @msg = @excep[3].concat(" "+@excep[4])
          @eliminado = false
        
        end
        
    respond_to do |f|

      f.js

    end

  end


  def buscar_persona
    
    if params[:tipo_documento_id].present? && params[:nacionalidad_id] && params[:documento].present?

      @persona = Persona.where("tipo_documento_id = ? and nacionalidad_id = ? and documento_persona = ?", params[:tipo_documento_id], params[:nacionalidad_id], params[:documento])  
 
    end

    respond_to do |f|

      f.json { render :json => @persona.first}

    end

  end


  def tutor_detalle
    
    @tutor_detalle = VTutorDetalle.where("tutor_id = ?", params[:tutor_id])


     respond_to do |f|

      f.js

    end
  
  end


  def agregar_tutor_detalle
    
    @tutor_detalle = TutorDetalle.new

   respond_to do |f|

      f.js

    end
  
  end


   def guardar_tutor_detalle
    
    @valido = true
    @msg = ""
    @guardado_ok = false

    unless params[:persona_documento].present?

      @valido = false
      @msg += " Debe Completar el campo Documento. \n"

    end

    unless params[:persona_nombre].present?

      @valido = false
      @msg += " El nombre del Paciente no puede estar vacío. \n"

    end

    unless params[:parentezco][:id].present?

      @valido = false
      @msg += " El apellido del Paciente no puede estar vacío. \n"

    end

    if @valido
      
      @tutor_Detalle = TutorDetalle.new()
      @tutor_Detalle.tutor_id = params[:tutor_id]
      @tutor_Detalle.paciente_id = params[:paciente_id]
      @tutor_Detalle.parentezco_id = params[:parentezco][:id]

        if @tutor_Detalle.save

          auditoria_nueva("registrar paciente asignado a tutor", "tutores_detalles", @tutor_Detalle)
          @guardado_ok = true
         
        end 

    end
  
    rescue Exception => exc  
    # dispone el mensaje de error 
    #puts "Aqui si muestra el error ".concat(exc.message)
      if exc.present?        
        @excep = exc.message.split(':')    
        @msg = @excep[3].concat(" "+@excep[4].to_s)
      
      end                

    respond_to do |f|

      f.js

    end
  
  end

  def eliminar_tutor_detalle

    @valido = true
    @msg = ""

    @tutor_detalle = TutorDetalle.find(params[:tutor_detalle_id])

    if @valido

      if @tutor_detalle.destroy

        auditoria_nueva("eliminar tutor detalle", "tutores_detalles", @tutor_detalle)

        @eliminado = true

      else

        @msg = "ERROR: No se ha podido eliminar el detalle del Tutor. Intente más tarde."

      end

    end

        rescue Exception => exc  
        # dispone el mensaje de error 
        #puts "Aqui si muestra el error ".concat(exc.message)
        if exc.present?        
          
          @excep = exc.message.split(':')    
          @msg = @excep
          @eliminado = false
        
        end
        
    respond_to do |f|

      f.js

    end
  
  end



end

app/helpers/tutores_helper.rb
module TutoresHelper

  def link_to_editar_tutor(persona_id)

      render partial: 'link_to_editar_tutor', locals: { persona_id: persona_id }
      
  end

  def link_to_tutor_detalle(tutor_id)

    render partial: 'link_to_tutor_detalle', locals: { tutor_id: tutor_id}

  end
  
end

app/views/tutores/_agregar.html.erb
<%= javascript_include_tag "modulos/pacientes.js" %>
<%= javascript_include_tag "sweetalert.min" %>
<%= stylesheet_link_tag "sweetalert" %>
<div class="modal-dialog">
      
  <div class="modal-content">
        
    <div class="modal-header" style="background:#e6e6e6;">
          
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title" id="myModalLabel">Agregar Tutor</h4>
      
    </div>

    <%= form_for @tutor, remote: true, url: tutores_guardar_url, html: { id: "form-agregar-tutor" }, method: 'POST' do |f| %>

      <%= hidden_field_tag :window_id, params[:window_id]%>
      <%= hidden_field_tag :persona_id%>

      <div class="modal-body">

        <div class="panel-body">

          <div class="col-sm-4"><%= label_tag nil, "Tipo de Documento #{attr_requerido}".html_safe, id: "lbl-tipo-documento-persona" %></div>

          <div class="col-sm-7"><%= collection_select :persona, :tipo_documento_id,  TipoDocumento.habilitados.ordenado_descripcion, :id, :descripcion, { include_blank: true}, {class: 'form-control input-sm'} %></div>

          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= label_tag nil, "Nacionalidad #{attr_requerido}".html_safe, id: "lbl-nacionalidad" %></div>
          <div class="col-sm-7"><%= collection_select :persona, :nacionalidad_id, Nacionalidad.ordenado_descripcion, :id, :descripcion, { include_blank: true}, {class: 'form-control input-sm'} %></div>
          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= label_tag nil, "N° Documento #{attr_requerido}".html_safe, id: "lbl-documento" %></div>
          <div class="col-sm-7"><%= text_field_tag :persona_documento, nil, class: 'form-control input-sm' %></div>
          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= label_tag nil, "Nombre #{attr_requerido}".html_safe, id: "lbl-nombre" %></div>
          <div class="col-sm-7"><%= text_field_tag :persona_nombre, nil, class: 'form-control input-sm', readonly: true %></div>
          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= label_tag nil, "Apellido #{attr_requerido}".html_safe, id: "lbl-apellido" %></div>
          <div class="col-sm-7"><%= text_field_tag :persona_apellido, nil, class: 'form-control input-sm', readonly: true %></div>
          <div class="col-sm-1"></div><br />
          <div class="col-sm-1"></div><br />



          
          <div class="col-sm-1"></div><br />
          <div id="buscar_perso">                                       
          </div>
        </div>        
       
      </div>

      <div class="modal-footer" style="background:#e6e6e6;">

        <%= link_to "Cerrar", "#", class: "btn btn-default", onclick: "$('##{params[:window_id]}').modal('hide');" %> 
        <%= link_to "Guardar","#" ,class: "btn btn-primary", id: "btn-guardar-tutor" %>
          
      </div>
 
    <%end %>

  </div>
  


<style type="text/css">

  #form-agregar-tutor label, #form-agregar-tutor input[type='text'], #form-agregar-tutor input[type='password'], #form-agregar-tutor select , #form-agregar-tutor input[type='checkbox']{ float:left; margin-top:5px;}
  #form-agregar-tutor br {clear:both; }
  #form-agregar-tutor label { width:200px;font-size:12px;margin-top:10px;}
  #form-agregar-tutor #persona_tipo_documento_persona_id { width:60%;}
  #form-agregar-tutor #persona_nacionalidad_id { width:60%;}
  #form-agregar-tutor #persona_documento { width:50%;}
 


</style>

<script type="text/javascript">

  setTimeout(function(){ 
    $("#persona_documento").focus();
    $("#persona_tipo_documento_id").val(1);
    $("#persona_nacionalidad_id").val(1);
  }, 1000);

  $("#persona_documento").bind("keydown", function(e){
      
    if(e.keyCode == 13 || e.keyCode == 9){
    buscar_persona_v2($("#persona_tipo_documento_id").val(), $("#persona_nacionalidad_id").val(), $("#persona_documento").val(), "<%= url_for(tutores_buscar_persona_path ) %>", "<%= url_for(personas_index_path( agregar: true))%>");
      return false;
    }
 
  })


  $("#btn-guardar-tutor").bind('click', function () {

      valido = true
      msg = ""

      if($("#persona_documento").val().length == 0){

        msg +="Ingrese número de documento.\n"
        valido = false
      
      }

      if($("#persona_nombre").val().length == 0){

        msg +="Nombre de persona no puede estar vacío.\n"
        valido = false
      
      }

      if($("#persona_apellido").val().length == 0){

        msg +="Apellido de persona no puede estar vacío.\n"
        valido = false
      
      }

      if (valido){

        swal({
          title: "Confirmar",
          text: "Al confirmar se podrá visualizar en la lista de tutores",
          type: "warning",
          showCancelButton: true,
          confirmButtonClass: "btn-confirm",
          confirmButtonText: "Confirmar",
          cancelButtonText: "Cancelar",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm) {
          if (isConfirm) {

            $("#form-agregar-tutor").submit();
            
          } 

        });

      }else{

        swal(msg);
      
      }

      return false;
    
    })

</script>

app/views/tutores/_agregar_tutor_detalle.html.erb
<%= javascript_include_tag "modulos/pacientes.js" %>
<div class="modal-dialog">
      
  <div class="modal-content">
        
    <div class="modal-header" style="background:#e6e6e6;">
          
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title" id="myModalLabel">Agregar Paciente</h4>
      
    </div>

    <%= form_for @tutor_detalle, remote: true, url: tutores_guardar_tutor_detalle_url, html: { id: "form-agregar-tutor-detalle" } do |f| %>

      <%= hidden_field_tag :window_id, params[:window_id]%>

      <%= hidden_field_tag :tutor_id, params[:tutor_id]%>

      <%= hidden_field_tag :paciente_id%>

      <div class="modal-body">

        <div class="panel-body">

          <div class="col-sm-4"><%= label_tag nil, "Tipo de Documento #{attr_requerido}".html_safe, id: "lbl-tipo-documento-persona" %></div>

          <div class="col-sm-7"><%= collection_select :persona, :tipo_documento_id,  TipoDocumento.habilitados.ordenado_descripcion, :id, :descripcion, { include_blank: true}, {class: 'form-control input-sm'} %></div>

          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= label_tag nil, "Nacionalidad #{attr_requerido}".html_safe, id: "lbl-nacionalidad" %></div>
          <div class="col-sm-7"><%= collection_select :persona, :nacionalidad_id, Nacionalidad.ordenado_descripcion, :id, :descripcion, { include_blank: true}, {class: 'form-control input-sm'} %></div>
          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= label_tag nil, "N° Documento #{attr_requerido}".html_safe, id: "lbl-documento" %></div>
          <div class="col-sm-7"><%= text_field_tag :persona_documento, nil, class: 'form-control input-sm' %></div>
          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= label_tag nil, "Nombre Paciente#{attr_requerido}".html_safe, id: "lbl-nombre" %></div>
          <div class="col-sm-7"><%= text_field_tag :persona_nombre, nil, class: 'form-control input-sm', readonly: true %></div>
          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= label_tag nil, "Apellido Paciente#{attr_requerido}".html_safe, id: "lbl-apellido" %></div>
          <div class="col-sm-7"><%= text_field_tag :persona_apellido, nil, class: 'form-control input-sm', readonly: true %></div>
          <div class="col-sm-1"></div><br />
          <div class="col-sm-1"></div><br />

          <div class="col-sm-4"><%= label_tag nil, "Parentezco del Tutor #{attr_requerido}".html_safe, id: "lbl-parentezco" %></div>
          <div class="col-sm-7"><%= collection_select :parentezco, :id, Parentezco.orden_01, :id, :descripcion, { include_blank: true}, {class: 'form-control input-sm'} %></div>
          <div class="col-sm-1"></div><br />



          
          <div class="col-sm-1"></div><br />
          <div id="buscar_perso">                                       
          </div>
        </div>        
       
      </div>

      <div class="modal-footer" style="background:#e6e6e6;">

        <%= link_to "Cerrar", "#", class: "btn btn-default", onclick: "$('##{params[:window_id]}').modal('hide');" %> 
        <%= link_to "Guardar","#", class: "btn btn-primary", id: "btn-guardar-paciente" %>
          
      </div>
    
    <% end %>

  </div>
</div>

<style type="text/css">

  #form-agregar-tutor-detalle label, #form-agregar-tutor-detalle input[type='text'] { float:left; margin-top:5px;}
  #form-agregar-tutor-detalle br {clear:both; }
  #form-agregar-tutor-detalle label { width:200px; font-size:12px;}

</style>

<script type="text/javascript">

  aplicar_datepicker2();

  setTimeout(function(){ 
    $("#persona_documento").focus();
    $("#persona_tipo_documento_id").val(1);
    $("#persona_nacionalidad_id").val(1);
  }, 1000);

  $("#persona_documento").bind("keydown", function(e){
      
    if(e.keyCode == 13 || e.keyCode == 9){
    buscar_paciente($("#persona_tipo_documento_id").val(), $("#persona_nacionalidad_id").val(), $("#persona_documento").val(), "<%= url_for(pacientes_buscar_paciente_path ) %>", "<%= url_for(pacientes_index_path( agregar: true))%>");
      return false;
    }
 
  })

  $("#btn-guardar-paciente").bind('click', function () {

      valido = true
      msg = ""

      if($("#persona_documento").val().length == 0){

        msg +="Ingrese número de documento.\n"
        valido = false
      
      }

      if($("#persona_nombre").val().length == 0){

        msg +="Nombre de persona no puede estar vacío.\n"
        valido = false
      
      }

      if($("#persona_apellido").val().length == 0){

        msg +="Apellido de persona no puede estar vacío.\n"
        valido = false
      
      }

      if($("#parentezco_id").val().length == 0){

        msg +="La relación de parentezco debe ser seleccionada.\n"
        valido = false
      
      }

      if (valido){

        swal({
          title: "Confirmar Tutoría",
          text: "Al confirmar el Paciente estará supervisado por el Tutor y éste podrá acceder a los datos generados por los avances del Paciente.",
          type: "warning",
          showCancelButton: true,
          confirmButtonClass: "btn-confirm",
          confirmButtonText: "Confirmar",
          cancelButtonText: "Cancelar",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm) {
          if (isConfirm) {

            $("#form-agregar-tutor-detalle").submit();
            
          } 

        });

      }else{

        swal(msg);
      
      }

      return false;
    
    })


</script>