config/routes.rb
Rails.application.routes.draw do

  
  namespace 'api' do
    namespace 'v1' do
  
      resources :personas
      resources :usuarios
  
    end
  end  
    
  #CRONTAB
  get "crontab_ultron/index"

  #JURISDICCIONES
  get "jurisdicciones/index"
  get "jurisdicciones/buscar_juridisccion_oferta" 

  #JURISDICCIONES
  get "informes/index"
  get "informes/indexa"
  get "informes/generar_pdf"

  #DETALLES DEBITOS
  post "detalles_debitos/lista"
  get "detalles_debitos/lista"
  get "detalles_debitos/agregar"
  post "detalles_debitos/guardar"
  get "detalles_debitos/eliminar"
  get "detalles_debitos/editar"
  post "detalles_debitos/actualizar"
  get "detalles_debitos/index"
 
  #DETALLES CREDITOS
  post "detalles_creditos/lista"
  get "detalles_creditos/lista"
  get "detalles_creditos/agregar"
  post "detalles_creditos/guardar"
  get "detalles_creditos/eliminar"
  get "detalles_creditos/editar"
  post "detalles_creditos/actualizar"
  get "detalles_creditos/index"

  #PRODUCCION
  get "produccion/index"
  get "produccion/lista"
  post "produccion/lista"
  get "produccion/agregar"
  post "produccion/guardar"
  get "produccion/eliminar"
  get "produccion/editar"
  post "produccion/actualizar"
  get "produccion/produccion_detalle_credito"
  get "produccion/produccion_detalle_debito"
  get "produccion/agregar_detalle_credito"
  get "produccion/agregar_detalle_debito"
  post "produccion/guardar_detalle_credito"
  post "produccion/guardar_detalle_debito"
  get "produccion/eliminar_produccion_detalle_credito"
  get "produccion/eliminar_produccion_detalle_debito"
  get "produccion/cambiar_estado_solicitado_a_en_progreso"
  get "produccion/cambiar_estado_en_progreso_a_finalizado"
  get "produccion/cambiar_estado_cobro"
  get "produccion/cambiar_estado_cobro_desconfirmar"
  get "produccion/planilla_resumen_produccion"
  get "produccion/planilla_resumen_produccion_pdf"
  get "produccion/planilla_resumen_produccion_cliente"
  get "produccion/planilla_resumen_produccion_cliente_pdf"
  
  #PACIENTES
  post "pacientes/lista"
  get "pacientes/lista"
  get "pacientes/agregar"
  post "pacientes/guardar"
  get "pacientes/eliminar"
  get "pacientes/editar"
  post "pacientes/actualizar"
  get "pacientes/index"
  get "pacientes/buscar_paciente"
  get "pacientes/buscar_persona"
  get "pacientes/buscar_paciente_cita"

  #PACIENTES DETALLES FONO
  get "pacientes_detalles_fono/paciente_detalle_fono"
  post "pacientes_detalles_fono/guardar_detalle_fono"

  #HISTORIALES PACIENTES
  post "historiales_pacientes/lista_pacientes"
  get "historiales_pacientes/lista_pacientes"
  get "historiales_pacientes/index"
  get "historiales_pacientes/historial_paciente_detalle_fono"
  get "historiales_pacientes/lista_citas"
  post "historiales_pacientes/lista_citas"
  get "historiales_pacientes/historial_cita_detalle_fono_terminado"
  


  #PROFESIONALES
  post "profesionales/lista"
  get "profesionales/lista"
  get "profesionales/agregar"
  post "profesionales/guardar"
  get "profesionales/eliminar"
  get "profesionales/editar"
  post "profesionales/actualizar"
  get "profesionales/index"
  get "profesionales/buscar_profesional"
  get "profesionales/buscar_persona"
  
  #TUTORES
  post "tutores/lista"
  get "tutores/lista"
  get "tutores/agregar"
  post "tutores/guardar"
  get "tutores/eliminar"
  get "tutores/editar"
  post "tutores/actualizar"
  get "tutores/index"
  get "tutores/buscar_tutor"
  get "tutores/buscar_persona"
  get "tutores/tutor_detalle"
  get "tutores/agregar_tutor_detalle"
  post "tutores/guardar_tutor_detalle"
  get "tutores/eliminar_tutor_detalle"

  #PRECIOS
  post "precios/lista"
  get "precios/lista"
  get "precios/agregar"
  post "precios/guardar"
  get "precios/eliminar"
  get "precios/editar"
  post "precios/actualizar"
  get "precios/index"
  get "precios/obtener_datos"
  get "precios/buscar_precio"
  get "precios/marcar_predeterminado"

  #CITAS
  get "citas/index"
  post "citas/lista"
  get "citas/lista"
  get "citas/agregar"
  post "citas/guardar"
  get "citas/editar"
  post "citas/actualizar"
  get "citas/eliminar"
  get "citas/cambiar_estado_cita_en_espera_a_en_consultorio"
  get "citas/cambiar_estado_cita_en_consultorio_a_terminado"
  get "citas/cambiar_estado_cobro_a_cobrado"
  get "citas/cambiar_estado_cobro_a_no_cobrado"
  get "citas/cambiar_estado_cita_terminado_a_en_consultorio"
  get "citas/postergar_cita"
  post "citas/guardar_postergar_cita"
  get "citas/imprimir_informe"
  get "citas/generar_informe_pdf"
  get "citas/cambiar_estado_cita_en_consultorio_a_en_espera"
  

  #CITAS DETALLES FONO
  get "citas_detalles_fono/cita_detalle_fono"
  post "citas_detalles_fono/guardar_cita_detalle_fono"
  get "citas_detalles_fono/emitir_resolucion"
  post "citas_detalles_fono/guardar_resolucion"
  get "citas_detalles_fono/adjuntar_resolucion"
  post "citas_detalles_fono/guardar_resolucion_adjunta"
  get "citas_detalles_fono/habilitar_descarga_archivo"
  get "citas_detalles_fono/deshabilitar_descarga_archivo"
  get "citas_detalles_fono/cita_detalle_fono_terminado"
  
  #PERSONAS
  post "personas/lista"
  get "personas/lista"
  get "personas/agregar"
  get "personas/agregar_persona_senatics"
  post "personas/guardar"
  post "personas/guardar_persona_senatics"
  get "personas/eliminar"
  get "personas/editar"
  post "personas/actualizar"
  get "personas/index"
  get "personas/mostrar_formulario"
  post "personas/unificar_persona"
  get "personas/obtener_datos"
  get "personas/buscar_persona_senatics"
  get "personas/buscar_chofer"
  

  #ROLES
  post "roles/lista"
  get "roles/lista"
  get "roles/agregar"
  post "roles/guardar"
  get "roles/eliminar"
  get "roles/editar"
  post "roles/actualizar"
  get "roles/accesos"
  get "roles/agregar_acceso"
  get "roles/guardar_acceso"
  get "roles/eliminar_acceso"
  get "roles/index"

  
  #CONTROLADORES
  post "controladores/lista"
  get "controladores/lista"
  get "controladores/agregar"
  post "controladores/guardar"
  get "controladores/eliminar"
  get "controladores/editar"
  post "controladores/actualizar"
  get "controladores/acciones"
  get "controladores/agregar_accion"
  post "controladores/guardar_accion"
  get "controladores/eliminar_accion"
  get "controladores/index"

  
  #USUARIOS
  get "usuarios/cambiar_perfil_actual"
  get "usuarios/mi_cuenta"
  post "usuarios/actualizar_mi_cuenta"
  post "usuarios/actualizar_mi_password"
  get "usuarios/perfiles"
  get "usuarios/agregar_perfil"
  get "usuarios/guardar_perfil"
  get "usuarios/eliminar_perfil"
  post "usuarios/actualizar_password"
  get "usuarios/reset_password"
  get "usuarios/perfiles"
  get 'usuarios/index'
  get 'usuarios/lista'
  post 'usuarios/lista'
  get "usuarios/agregar"
  post "usuarios/guardar"
  get "usuarios/eliminar"
  get "usuarios/editar"
  post "usuarios/actualizar"
  get 'usuarios/buscar_persona'
  post 'usuarios/cambiar_estado_usuario'

  #LOGIN
  get 'login' => "usuarios_sessions#new",      :as => :login
  get 'logout' => "usuarios_sessions#destroy", :as => :logout
  post "usuarios_sessions/create"
  get "usuarios_sessions/acceso_denegado"
  get "usuarios_sessions/new"  
  get "usuarios_sessions/mantenimiento"  

  get "principal/buscar_institucion"
  get "principal/buscar_persona"
  get "principal/buscar_usuario"
  post "principal/guardar_recuperar_password"
  get "principal/recuperar_password"
  post "principal/guardar_usuario"
  get "principal/activar_cuenta"
  get "principal/agregar_usuario"
  get "contactos" => "principal#contactos", :as => :contactos
  get "index" => "principal#index", :as => :index
  get "about" => "principal#about", :as => :about
  get "legal" => "principal#legal", :as => :legal
  get "index" => "principal#index", :as => :indexv
	
	

  root 'principal#index'
  
  get "application/autocompletar" => 'application#autocompletar', :as => :autocompletar

  #INFORMACIONES
  get "informaciones/index"
  get "informaciones/lista"
  post "informaciones/lista"
	get "informaciones/perfiles"
	get "informaciones/enlaces"
  get "informaciones/agregar"
  post "informaciones/guardar"
	get "informaciones/agregar_enlace"
	get "informaciones/guardar_enlace"
	post "informaciones/guardar_enlace"
	get "informaciones/agregar_perfil"
  get "informaciones/guardar_perfil"
  get "informaciones/eliminar"
  get "informaciones/editar"
  post "informaciones/actualizar"
	get "informaciones/editar_enlace"
	post "informaciones/actualizar_enlace"
  get "informaciones/eliminar_enlace"
  get "informaciones/eliminar_rol"

end

app/helpers/informaciones_helper.rb
module InformacionesHelper

  def link_to_editar_informacion(usuario)
    render partial: 'link_to_editar_informacion', locals: { usuario: usuario }
  end
	
  def link_to_editar_enlace(usuario)
    render partial: 'link_to_editar_enlace', locals: { usuario: usuario }
  end

  def link_to_perfiles(usuario)

    render partial: "link_to_perfiles", locals: { usuario: usuario}

  end
	
	def link_to_enlaces(usuario)

    render partial: "link_to_enlaces", locals: { usuario: usuario}

  end

 

end

app/views/informaciones/_agregar_enlace.html.erb
<%= javascript_include_tag "modulos/usuarios.js" %>
<div class="modal-dialog" style = "width:60%; align-content: center;">
      
  <div class="modal-content">
        
    <div class="modal-header" style="background:#e6e6e6;">
          
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title" id="myModalLabel">Agregar</h4>
      
    </div>

    <%= form_for @enlace, remote: true, url: informaciones_guardar_enlace_url, html: { id: "form-agregar-enlace" }, method: 'POST' do |f| %>

      
	  <%= hidden_field_tag :usuario_id, params[:usuario_id] %>
	  <%= hidden_field_tag :informacion_id, params[:informacion_id] %>
	  <%= hidden_field_tag :window_id, params[:window_id]%>

      <div class="modal-body">

        <div class="panel-body">
			
		  <div class="col-sm-4"><%= label_tag nil, "Titulo #{attr_requerido}".html_safe, id: "lbl-titulo" %></div>
          <div class="col-sm-7"><%= text_field_tag :titulo, nil, class: 'form-control input-sm' %></div>
          <div class="col-sm-1"></div><br /><br />
		  
		  <div class="col-sm-4"><%= label_tag nil, "Enlace #{attr_requerido}".html_safe, id: "lbl-enlace" %></div>
          <div class="col-sm-7"><%= text_field_tag :enlace, nil, class: 'form-control input-sm' %></div>
          <div class="col-sm-1"></div><br /><br />
		  
		  
        </div>        
       
      </div>

      <div class="modal-footer" style="background:#e6e6e6;">

        <%= link_to "Cerrar", "#", class: "btn btn-default", onclick: "$('##{params[:window_id]}').modal('hide');" %> 
        <%= f.submit "Guardar", class: "btn btn-primary", id: "btn-guardar-enlace" %>
          
      </div>

    <% end %>

  </div>
  
</div>

<style type="text/css">

  #form-agregar-enlace label, #form-agregar-enlace input[type='text'], #form-agregar-enlace input[type='password'], #form-agregar-enlace select , #form-agregar-enlace input[type='checkbox']{ float:left; margin-top:5px;}
  #form-agregar-enlace br {clear:both; }
  #form-agregar-enlace label { width:200px;font-size:12px;margin-top:10px;}
  #form-agregar-enlace #persona_tipo_documento_persona_id { width:60%;}
  #form-agregar-enlace #persona_nacionalidad_id { width:60%;}
  #form-agregar-enlace #persona_documento { width:50%;}
  #form-agregar-enlace #usuario_password { width:60%;}
  #form-agregar-enlace #usuario_password_confirmation { width:60%;}
  #form-agregar-enlace #notificar_usuario { width:10%;}


</style>

<script type="text/javascript">
  aplicar_datepicker();

  setTimeout(function(){ 
    $("#titulo").focus();
    $("#persona_tipo_documento_id").val(1);
    $("#persona_nacionalidad_id").val(1);
  }, 1000);

 
</script>

app/views/informaciones/_editar.html.erb
<%= javascript_include_tag "modulos/usuarios.js" %>
<div class="modal-dialog" style = "width:60%; align-content: center;">
      
  <div class="modal-content">
        
    <div class="modal-header" style="background:#e6e6e6;">
          
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title" id="myModalLabel">Editar Información</h4>
      
    </div>

    <%= form_for @informacion, remote: true, url: informaciones_actualizar_url, html: { id: "form-editar-informacion" }, method: 'POST' do |f| %>

      <%= f.hidden_field :id %>
      <%= hidden_field_tag :window_id, params[:window_id]%>

      <div class="modal-body">

        <div class="panel-body">

          <div class="col-sm-4"><%= label_tag nil, "Titulo #{attr_requerido}".html_safe, id: "lbl-titulo" %></div>
          <div class="col-sm-7"><%= text_field_tag :titulo, nil, class: 'form-control input-sm' %></div>
          <div class="col-sm-1"></div><br /><br />
		  
		  <div class="col-sm-4"><%= label_tag nil, "Descripción #{attr_requerido}".html_safe, id: "lbl-descripcion" %></div>
          <div class="col-sm-8"><%= text_area_tag :descripcion,nil, class: 'form-control input-sm', style: "width:87%;" %></div><br /><br />
		  
		  
		
	      <div class="col-sm-4"><%= label_tag nil, "Fecha Publicación #{attr_requerido}".html_safe %></div>
		  <!--<div class="col-sm-4"><%#= label_tag nil, "Fecha Publicación #{attr_requerido}".html_safe, id: "lbl-fecha" %></div>-->
		  
                <div class="col-sm-8">
                    <div class="input-group date" , style="width:26%;">
                      <%= f.text_field :fecha_publicacion, :value => @informacion.fecha_publicacion.present? ? @informacion.fecha_publicacion.strftime('%d/%m/%Y') : nil ,:size => 8, :class => 'form-control input-sm' %>
                      <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                    </div>
				
				</div>

          <div class="col-md-1"></div><br /><br />
          
        </div>
        
      </div>

      <div class="modal-footer" style="background:#e6e6e6;">

        <%= link_to "Cerrar", "#", class: "btn btn-default", onclick: "$('##{params[:window_id]}').modal('hide');" %> 
        <%= f.submit "Actualizar", class: "btn btn-primary", id: "btn-actualizar-informacion" %>
          
      </div>

    <% end %>

  </div>
</div>

<style type="text/css">

  /*#form-editar-informacion label, #form-editar-informacion input[type='text'] { float:left; margin-top:5px;}*/
  #form-editar-informacion label, #form-editar-informacion input[type='text'], #form-editar-informacion input[type='password'], #form-editar-informacion select , #form-editar-informacion input[type='checkbox']{ float:left; margin-top:5px;}
  #form-editar-informacion br {clear:both; }
  #form-editar-informacion label { width:200px;text-align:left;  }

</style>

<script type="text/javascript">
  aplicar_datepicker();

  setTimeout(function(){ 
    $("#titulo").focus();
  }, 1000);
  
  
  
  //------------------- RECUPERAR DATOS -------------------------//
    <% if @informacion.present? %>

    setTimeout(function(){
        $("#titulo").val('<%= @informacion.titulo %>');
        $("#descripcion").val('<%= @informacion.contenido %>');
		//$("#informacion_fecha_publicacion").val('<%#= @informacion.fecha_publicacion %>');
		


    }, 10);
    <% end %>

</script>

app/views/informaciones/_editar_enlace.html.erb
<%= javascript_include_tag "modulos/usuarios.js" %>
<div class="modal-dialog" style = "width:60%; align-content: center;">
      
  <div class="modal-content">
        
    <div class="modal-header" style="background:#e6e6e6;">
          
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title" id="myModalLabel">Editar Enlace</h4>
      
    </div>

    <%= form_for @enlace, remote: true, url: informaciones_actualizar_enlace_url, html: { id: "form-editar-informacion" }, method: 'POST' do |f| %>

      <%= f.hidden_field :id %>
      <%= hidden_field_tag :window_id, params[:window_id]%>
	  
	  <%= hidden_field_tag :informacion_id, params[:informacion_id] %>

      <div class="modal-body">

        <div class="panel-body">

          <div class="col-sm-4"><%= label_tag nil, "Titulo #{attr_requerido}".html_safe, id: "lbl-titulo" %></div>
          <div class="col-sm-7"><%= text_field_tag :titulo, nil, class: 'form-control input-sm' %></div>
          <div class="col-sm-1"></div><br /><br />
		  
		  <div class="col-sm-4"><%= label_tag nil, "Enlace #{attr_requerido}".html_safe, id: "lbl-enlace" %></div>
          <div class="col-sm-7"><%= text_field_tag :enlace, nil, class: 'form-control input-sm' %></div>
          <div class="col-sm-1"></div><br /><br />

          <div class="col-md-1"></div><br /><br />
          
        </div>
        
      </div>

      <div class="modal-footer" style="background:#e6e6e6;">

        <%= link_to "Cerrar", "#", class: "btn btn-default", onclick: "$('##{params[:window_id]}').modal('hide');" %> 
        <%= f.submit "Actualizar", class: "btn btn-primary", id: "btn-actualizar-informacion" %>
          
      </div>

    <% end %>

  </div>
</div>

<style type="text/css">

  #form-editar-informacion label, #form-editar-informacion input[type='text'] { float:left; margin-top:5px;}
  #form-editar-informacion br {clear:both; }
  #form-editar-informacion label { width:200px;}

</style>

<script type="text/javascript">
  aplicar_datepicker();

  setTimeout(function(){ 
    $("#titulo").focus();
  }, 1000);
  
  
  
  //------------------- RECUPERAR DATOS -------------------------//
    <% if @enlace.present? %>

    setTimeout(function(){
        $("#titulo").val('<%= @enlace.titulo %>');
        $("#enlace").val('<%= @enlace.enlace %>');
		


    }, 10);
    <% end %>

</script>

app/views/informaciones/_footer.html.erb
<% if usuarios.present? %>

  <tr id="tab-paginacion">
    <td colspan="9" style="text-align:center;"><div class="flickr_pagination"><%= ajax_will_paginate usuarios, :params => params %></div></td>
  </tr>

  <tr id="tab-cantidad-registros" style="background:#e6e6e6;">
    <td colspan="9">Cantidad de registros encontrados: <%= @total_encontrados %> de <%= @total_registros %></td>
  </tr>

<% end %>

app/views/informaciones/_link_to_editar_enlace.html.erb
<%= link_to icon_editar, "#", id: "link-to-editar-enlace-#{usuario.id}", class: 'btn btn-warning btn-xs', title: 'Haga click para editar.', onclick: "$('.modal').html('');return false;" %>

<%= modal_window( window_id: "modal-window-editar-enlace", link_to_id: "#link-to-editar-enlace-#{usuario.id}", url: informaciones_editar_enlace_path( window_id: "modal-window-editar-informacion", id: usuario.id, informacion_id: usuario.informacion_id) )%>

app/views/informaciones/_link_to_editar_informacion.html.erb
<%= link_to icon_editar, "#", id: "link-to-editar-informacion-#{usuario.id}", class: 'btn btn-warning btn-xs', title: 'Haga click para editar la informacion.', onclick: "$('.modal').html('');return false;" %>

<%= modal_window( window_id: "modal-window-editar-informacion", link_to_id: "#link-to-editar-informacion-#{usuario.id}", url: informaciones_editar_path( window_id: "modal-window-editar-informacion", id: usuario.id) )%>

app/views/informaciones/_lista.html.erb
<% if usuarios.present? %>

  <% usuarios.each do |u| %>

    <tr>

      <td style="width:50px;"><%= u.id %></td>
      <td><%= u.titulo %></td>
      <td><%= u.contenido %></td>
      <td><%= u.fecha_publicacion.strftime("%d/%m/%Y") %></td>
      <td style="text-align:center;width:150px;">
	 <%= link_to_enlaces(u) %>
        <%= link_to_perfiles(u) %>
        <%= link_to_editar_informacion(u) %>
        <%= link_to icon_eliminar, informaciones_eliminar_path(id: u.id), remote: true, class: "btn btn-danger btn-xs", title: 'Haga click para eliminar', data: { confirm: "Está seguro de eliminar ?"} %> 
      </td>

    </tr>

  <% end %>

<% else %>

  <tr>

    <td colspan="9"><p class='none-result'>No se han encontrado resultados.</p></td>

  </tr>

<% end %>

app/views/informaciones/_perfiles.html.erb
<td colspan="9">

  <div style="background: #e6e6e6; margin:15px;padding:15px;border-radius:10px;">

    <div>

      <div class="col-sm-12" style="border-bottom: 2px dashed #b6b6b6;margin-bottom:5px;padding:0px;">
        <h3 style="float:left;margin-top:5px;">Roles</h3>
        <%= link_to "<i class='glyphicon glyphicon-plus-sign'></i> agregar".html_safe, "#", id: "link-to-agregar-perfil", class: "btn btn-primary btn-xs", style: "float:right;", onclick: "$('.modal').html('');return false;" %>
      </div>

    </div>

    <div style="clear:both;"></div>
   
    <div class="panel-body">
      
      <div class="table-responsive" id="table-perfiles">
          
        <table class="table table-bordered table-hover table-striped display dataTable" aria-describedby="example_info">
            
          <thead>
              
            <tr role="row">
              
              <th>ID</th>
              <th>Rol</th>
              <th style='text-align:right;'></th>
              
            </tr>
            
          </thead>
       
          <tbody id="perfiles-lista">

            <% if @info_roles.present? %>
            
              <% @info_roles.each do |p|%>

                <tr>
                  <td><%= p.id %></td>
				  <td><%= p.rol.descripcion if p.rol %></td>
                  <td style="width: 50px;text-align:right;">
                    <%= link_to "<i class='glyphicon glyphicon-remove'></i>".html_safe, informaciones_eliminar_rol_path(id: p.id, informacion_id: p.informacion_id), remote: true, class: 'btn btn-danger btn-xs', title: "Haga click para eliminar el rol", data: {confirm: 'Esta seguro de eliminar este rol ?'} %>
                  </td>

                </tr>

              <% end %>

            <% else %>

              <tr><td colspan=9>No se han encontrado datos.</td></tr>

            <% end %>
                
          </tbody>
              
        </table>
        
      </div>
      
    </div>
    
  </div>

  <%= modal_window( window_id: "modal-window-agregar-perfil", link_to_id: "#link-to-agregar-perfil", url: informaciones_agregar_perfil_path( window_id: "modal-window-agregar-perfil", usuario_id: params[:usuario_id], informacion_id: params[:informacion_id]) )%>

</td>

app/views/informaciones/editar_enlace.js.erb
$("#<%= params[:window_id]%>").html('');
$("#<%= params[:window_id]%>").html("<%= escape_javascript(render :partial => 'editar_enlace')%>");
$("#<%= params[:window_id]%>").modal('show');

app/views/informaciones/eliminar.js.erb
<% if @eliminado %>

   $("<div class='col-sm-12' id='msg-eliminar-usuario' style='color:#000;padding-top:5px;font-size:10px;background:#d6ffd6;border-radius:5px;text-align:center;'>Eliminado exitosamente.</div>").insertBefore("#table-informaciones");
   $("#form-buscar-informaciones").submit();
    setTimeout(function(){ $("#msg-eliminar-informaciones").remove(); }, 3000);

<% else %>

  $("<div class='col-sm-12' id='msg-eliminar-usuario' style='color:#000;padding-top:5px;font-size:10px;background: #f8dfdf;border-radius:5px;text-align:center;'><%= @msg.html_safe %></div>").insertBefore("#table-informaciones");
  setTimeout(function(){ $("#msg-eliminar-informaciones").remove(); }, 3000);

<% end %>

app/views/informaciones/eliminar_rol.js.erb
<% if @eliminado %>
alert('Rol Eliminado Exitosamente');

  setTimeout(function(){ 
    $("#link-to-perfiles-<%= @informacion_id %>").trigger('click');
    $("#link-to-perfiles-<%= @informacion_id %>").trigger('click');
   }, 3000);

<% else %>

alert('Ha ocurrido un error al intentar eliminar el rol.')
<% end %>

app/views/informaciones/enlaces.js.erb
$("#enlaces-<%= params[:informacion_id]%>").html("<%= escape_javascript(render :partial => "enlaces") %>");

app/views/informaciones/lista.js.erb
$("#usuarios-lista").html("<%= escape_javascript(render partial: "lista", locals: { usuarios: @usuarios}) %>");
$("#usuarios-footer").html("<%= escape_javascript(render :partial => "footer", :locals => { usuarios: @usuarios }) %>");

app/views/informaciones/perfiles.js.erb
$("#perfiles-<%= params[:informacion_id]%>").html("<%= escape_javascript(render :partial => "perfiles") %>");